CREATE DATABASE IF NOT EXISTS ha_db CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE ha_db;

CREATE TABLE IF NOT EXISTS proxmox_creds (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  credential_name VARCHAR(255) NOT NULL,
  api_user VARCHAR(255) NOT NULL,
  api_token VARCHAR(255) NOT NULL,
  api_url VARCHAR(255) NOT NULL,
  api_token_id VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS servers (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  new_vm_name VARCHAR(128) NOT NULL UNIQUE,
  vm_memory INT UNSIGNED NOT NULL,
  vm_cores INT UNSIGNED NOT NULL,
  ci_user VARCHAR(64) NOT NULL,
  ci_password VARCHAR(255) NOT NULL,
  mysql_password VARCHAR(255) NOT NULL,
  ipconfig0 VARCHAR(255) NOT NULL,
  is_master VARCHAR(128) NOT NULL,
  provider VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'queued',
  ip VARCHAR(64) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;